name: remove pr deploy
on:
  pull_request:
    types: closed

permissions:
  id-token: write
  contents: read

jobs:
  remove-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.CI_ROLE }}
          role-session-name: LagomPopcornSession
      - name: Install & remove stack
        run: |
          yarn --frozen-lockfile
          yarn sst remove --stage pr-${{ github.event.pull_request.id }}
